-- AlterTable
ALTER TABLE "CheckGoal" ADD COLUMN     "createdDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "registeredDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
