//* Libraries imports
import type { Metadata } from "next";
import { Inter } from "next/font/google";

//* Styles imports
import "./globals.css";

//* Components imports
import { QueryClient } from "@/components/wrapper/query-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClient>
          {children}
        </QueryClient>
      </body>
    </html>
  );
}
